# Generated by Django 4.2.2 on 2023-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_customerreview_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.CharField(default="", max_length=500),
        ),
    ]
