# Generated by Django 4.2.2 on 2023-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="checkout",
            field=models.BooleanField(default=False),
        ),
    ]
