# Generated by Django 4.2.2 on 2023-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_cart_checkout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=500)),
                ("star", models.IntegerField()),
                ("comment", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
