# Generated by Django 4.2.2 on 2023-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=300)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="product", options={"ordering": ("id", "price", "name")},
        ),
    ]
